### ISSUE TITLE
Repository ownership 

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/BlueLL#16]
### Expand ownership

Development and compatibility updates of BlueLL have been rare. @jdlrobson has displayed skills and interest in maintaining this skin compatibility with the latest mediawiki releases (see #14). Also, I'm inviting @jdlrobson to be a co-owner of this repository.

### Transfert ?
In 2024, Lingualibre development of its v3.0 will lead us to fully phase out mediawiki and BlueLL skin.

This repository will therefore become orphaned.

If so, I don't see the practical point to keep BlueLL's code under the "LinguaLibre" umbrella and github ownership. When the time comes and as it is customary in Open Source community, we could transfer the github ownership to active open source maintainer(s). 

If this is confirmed a rapid concensus building among devs will be welcome.

### Options

| Lingualibre devs | External devs | Solution |
| --- | --- | --- |
| Stop maintaining BlueLL | No one interested to continue | Archive repository
| Stop maintaining BlueLL | Want to edit occasionally, don't want ownership | Keep repo here, grant maintainer rights
| Stop maintaining BlueLL | Want to edit, want ownership | Grant maintainer rights, transfer ownership

### Todo
- [x] Invitation sent to active contributors @jdlrobson @mamarto
- [ ] Invitation accepted 
- [ ] Build concensus among past contributors 
- [ ] Transfer ownership https://github.com/lingua-libre/BlueLL/transfer
- [ ] Fill https://github.com/lingua-libre/BlueLL with a single README.md pointing to the new repository address.

**Comment by hugolpz** [comment]
- [x] @jdlrobson is maintainer
- [ ] @mamarto : I sent you an invitation as maintainer.

@jdlrobson, @mamarto , no Lingualibre dev will edit this skin anymore, we are shifting to another stack. 
Please let me know if you are interested to continue occasional editing of this skin here or to get ownership of it.

**Comment by mamarto** [comment]
> * [x]  @jdlrobson is maintainer
> * [x]  @mamarto : decline invitation.
> 
> @jdlrobson, @mamarto , no Lingualibre dev will edit this skin anymore, we are shifting to another stack. Please let me know if you are interested to continue occasional editing of this skin here or to get ownership of it.

Hi @hugolpz - I'm only porting a patch that wasn't written by me, so I can't accept the invitation to be a maintainer since I'm not contributing to this repository.

**Comment by hugolpz** [comment]
@mamarto , thank for the quick answer ! 👍🏼

**Comment by jdlrobson** [comment]
Are there any objections to moving this to Wikimedia's Gerrit so I can share maintenance with other Wikimedians?
